# .streamlit/secrets.toml 

[connections.snowflake]
account = "IGUPPMX-DM38954"
user = "samart"
password = "L1@uren7t"
role = "sysadmin"
warehouse = "compute_wh"
database = "smoothies"
schema = "public"
client_session_keep_alive = true 
